#!/bin/bash
if ((xrandr | grep "VGA1 connected") && (xrandr | grep "HDMI1 connected")); then
    xrandr --output LVDS1 --off --output VGA1 --auto --output HDMI1 --auto --right-of VGA1
    echo "DUAL MONITOR"
elif (xrandr | grep "VGA1 connected"); then
    xrandr --output LVDS1 --off --output VGA1 --auto
    echo "VGA1"
elif (xrandr | grep "HDMI1 connected"); then
        xrandr --output LVDS1 --off --output HDMI1 --auto
        echo "HDMI1"
else
    xrandr --output VGA1 --off --output HDMI1 --off --output LVDS1 --auto
    echo "LVDS1"
fi
echo "setup-xrandr `date`" >> /home/tom/.i3/log
